const PriceBudgetPackage = {
  title: {
    name: "Pricing-Budget",
    price: "1999",
  },
  sections: [
    {
      title: "Overview",
      type: "text",
      content:
        "Our Budget Package offers essential construction services at an affordable price point, with basic materials and fundamental design elements for budget-conscious clients.",
    },
    {
      title: "Design",
      type: "list",
      items: [
        "ELEVATION DESIGN : (3D)",
        "HALF LAYOUT : ALL FLOORS (3D)",
        "ELECTRICAL DRAWINGS : ALL FLOORS (2D)",
        "PLUMBING DRAWING : ALL FLOORS (2D)",
        "WORKING DRAWING : ALL FLOORS (2D)",
        "(CLIENT SCOPE)*",
      ],
    },
    {
      title: "Project Management",
      type: "list",
      items: [
        "Site Engineer : Weekly 3 Days Site Vsit",
        "Architect : Paid Design support",
      ],
    },
    {
      title: "Structure",
      type: "list",
      items: [
        "Basement Height : 2.5 feet",
        "Steel : ANY ISI BRAND",
        "Bricks : RED BRICKS",
        "Cement : ANY ISI BRAND",
        "Fine Aggregate : M-SAND/P-SAND",
        "Concrete Grade : M20",
        "Ceiling Height : 9.5 Feet",
        "Basement Plastering : NIL",
        "Parapet Wall : 3' Feet Height | 6\" Thick",
        "Cement: ANY ISI BRAND",
        "Steel: ANY ISI BRAND",
        "Fine Aggregate: M-SAND/P-SAND",
        "Bricks: RED BRICKS",
        "Wire: ORBIT OR EQUIVALENT",
        "Switches: ANY ISI BRAND",
        "Water Tank: ANY ISI BRANDS 750 LTR",
      ],
    },
    {
      title: "Plumbing & Sanitary",
      type: "list",
      items: [
        "Plumbing (Concealed CPVC): ANY ISI BRAND",
        "Plumbing Open PVC: ANY ISI BRAND",
        "Sanitary Fittings: ANY ISI BRAND",
        "Taps & Valves: METRO/WATERMAN",
        "Bathroom Floor Tile: ANTISKID 1X1 TILES BELOW 35/-",
        "Bathroom Wall Tile & Height: CERAMIC 1X1 TILES BELOW 35/-7 FEET",
        "Kitchen Wall Tile: DADO TILE 1X1 (2 FEET WALL HEIGHT) 35/-",
      ],
    },
    {
      title: "Doors & Windows",
      type: "list",
      items: [
        "Main Door Frame: READYMADE DOOR FRAMES",
        "Main Door: READYMADE DOOR SINGLE DOOR PLAIN",
        "Bedroom Door Frames: READYMADE DOOR",
        "Bedroom Door: FLUSH DOORS BUDGET BELOW 2500/-",
        "Bathroom Door: PVC DOORS & FRAME",
        "Windows: UPVC WITH GLASS 4MM",
        "Ventilators: UPVC LOUVERS",
      ],
    },
    {
      title: "Flooring & Finishing",
      type: "list",
      items: [
        "Interior Paint: ANY ISI BRAND",
        "Exterior Paint: ASIAN ACE OR EQUIVALENT BRANDS",
        "Handrails for Staircase: M.S Grill",
        "Staircase Flooring: TILES BELOW 40/- PER SQFT",
        "Kitchen Counter Top: GRANITE BELOW 60/-",
        "Terrace: NORMAL CEMENT FLOORING",
        "Floor Tile: VERTIFIED 1X1 TILES BELOW 35/-",
      ],
    },
    {
      title: "Additional Features",
      type: "list",
      items: [
        "Carparking/Portico/Balcony: ANTISKID TILES 35/-",
        "AC Point Provisions: ONLY ONE BEDROOM",
        "General Extra: -",
        "Team Supports: SITE ENG ONE TIME SITE VISIT DAILY",
        "Locks: ANY ISI BRANDS",
        "Design & Drawings: CLIENT SCOPE",
        "General Extra: ANTI-TERMITE TREATMENT (CLIENT SCOPE)*",
        "BASEMENT PLASTERING: YES (CLIENT SCOPE)*",
        "AC POINT PROVISIONS: ONLY ONE BEDROOM - OTHERS (CLIENT SCOPE)*",
      ],
    },
  ],
};

const standardPackage = {
  title: {
    name: "Standard Package",
    price: "2199",
  },
  sections: [
    {
      title: "Overview",
      type: "text",
      content:
        "Our Standard Package offers quality construction at an affordable price point, with essential features and finishes for your home building needs.",
    },
    {
      title: "Design",
      type: "list",
      items: [
        "SCHEME DRAWING : ALL FLOORS (2D)",
        "ELEVATION DESIGN : (3D)",
        "HALF LAYOUT : ALL FLOORS (3D)",
        "WORKING DRAWING : ALL FLOORS (2D)",
      ],
    },
    {
      title: "Project Management",
      type: "list",
      items: [
        "Site Engineer : Weekly 3 Days Site Vsit",
        "Architect : Support Till Design Completion",
      ],
    },
    {
      title: "Structure",
      type: "list",
      items: [
        "Basement Height : 3 feet",
        "Steel : THIRUMALA",
        "Bricks : RED BRICKS/FLY ASH BRICKS",
        "Cement : ZUARI/NAGAJUNA/PRIYA",
        "Fine Aggregate : M-SAND/P-SAND",
        "Concrete Grade : M20 | RMC for Roof",
        "Ceiling Height : 10 Feet",
        "Basement Plastering : CLIENT SCOPE",
        "Cement: ZUARI/NAGAJUNA/PRIYA",
        "Fine Aggregate: M-SAND/P-SAND",
        "Bricks: RED BRICKS/FLY ASH BRICKS",
        "Wire: KUNDAN OR EQUIVALENT",
        "Switches: HI-FI/KUNDAN OR EQUIVALENT",
        "Water Tank: STAR (OR) AQUATECH 1000 LTR",
      ],
    },
    {
      title: "Plumbing & Sanitary",
      type: "list",
      items: [
        "Plumbing (Concealed CPVC): SUPREME/JAIN PIPES OR EQUIVALENT",
        "Plumbing Open PVC: TROOP /STAR OR EQUIVALENT",
        "Sanitary Fittings: NEYCER",
        "Taps & Valves: WATER TECH/GURU",
        "Bathroom Floor Tile: ANTISKID 1X1 TILES BELOW 40/-",
        "Bathroom Wall Tile & Height: CERAMIC 1X2 TILES BELOW 40/-7 FEET",
        "Kitchen Wall Tile: DADO TILE 2X2 (2 FEET WALL HEIGHT) 40/-",
      ],
    },
    {
      title: "Doors & Windows",
      type: "list",
      items: [
        "Main Door Frame: READY MADE TEAK FRAME",
        "Main Door: READYMADE DOOR SINGLE DOOR SIMPLE DESG",
        "Bedroom Door Frames: READY MADE TEAK FRAME",
        "Bedroom Door: FLUSH DOORS BUDGET BELOW 3500/-",
        "Bathroom Door: PVC FRAMES & DOORS",
        "Windows: UPVC WITH GLASS 4MM WITH PINNED GLASS",
        "Ventilators: UPVC LOUVERS",
      ],
    },
    {
      title: "Flooring & Finishing",
      type: "list",
      items: [
        "Interior Paint: ASIAN PAINTS TRACTOR EMULSION",
        "Exterior Paint: ASIAN ACE OR EQUIVALENT BRANDS",
        "Handrails for Staircase: M.S.GRILL",
        "Staircase Flooring: GRANITE BELOW 60/- PER SQFT",
        "Kitchen Counter Top: GRANITE BELOW 80/- PER SQFT",
        "Terrace: OXIDE FLOORING",
        "Floor Tile: VERTIFIED 2X2 TILES BELOW 40/-",
      ],
    },
    {
      title: "Additional Features",
      type: "list",
      items: [
        "Carparking/Portico/Balcony: ANTISKID TILES 40/-",
        "AC Point Provisions: ONLY IN BEDROOMS",
        "General Extra: -",
        "Team Supports: SITE ENG VISIT DAILY",
        "Locks: ANY ISI BRANDS",
        "Design & Drawings: FLOOR PLAN 2D & ELEVATION",
      ],
    },
  ],
};

const premiumPackage = {
  title: {
    name: "Premium Package",
    price: "2350",
  },
  sections: [
    {
      title: "Overview",
      type: "text",
      content:
        "Our Premium Package offers enhanced quality and additional features for discerning homeowners who want superior finishes and more comprehensive services.",
    },
    {
      title: "Design",
      type: "list",
      items: [
        "SCHEME DRAWING : ALL FLOORS (2D)",
        "ELEVATION DESIGN : (3D)",
        "HALF LAYOUT : ALL FLOORS (3D)",
        "WORKING DRAWING : ALL FLOORS (2D)",
        "STRUCTURAL DRAWINGS",
        "FURNITURE LAYOUT : ALL FLOORS (2D)",
        "ELEVATION DETAIL DRAWING : (2D)",
      ],
    },
    {
      title: "Project Management",
      type: "list",
      items: [
        "Site Engineer : Weekly 3 Days Site Vsit",
        "Architect : Dedicated Architect till design",
      ],
    },
    {
      title: "Structure",
      type: "list",
      items: [
        "Basement Height : 3.5 feet",
        "Steel : AGNI/SURYADEV/ARS",
        "Bricks : RED BRICKS/AAC BLOCKS/INTERLOCKING",
        "Cement : DALMIA/CHETTINADU/RAMCO",
        "Fine Aggregate : M-SAND/P-SAND",
        "Concrete Grade : M20 | RMC for Roof",
        "Ceiling Height : 10.5 Feet (FFL to FFL)",
        "Basement Plastering : YES",
        "Parapet Wall : 3.5' Feet Height | 6\" Thick",
        "Cement: DALMIA/CHETTINADU/RAMCO",
        "Fine Aggregate: M-SAND/P-SAND",
        "Bricks: RED BRICKS/AAC BLOCKS/INTERLOCKING",
        "Wire: HAVELS OR EQUIVALENT",
        "Switches: CONA/WIPRO OR EQUIVALENT",
        "Water Tank: VECTUS 1000LTR",
      ],
    },
    {
      title: "Plumbing & Sanitary",
      type: "list",
      items: [
        "Plumbing (Concealed CPVC): ARUNACHALA /ASTRAL",
        "Plumbing Open PVC: ARUNACHALA /ALWA",
        "Sanitary Fittings: CERA/HINDWARE/RAK",
        "Taps & Valves: PARRYWARE/SOMANY/HINDWARE/RAK",
        "Bathroom Floor Tile: ANTISKID 1X15 TILES BELOW 45/-",
        "Bathroom Wall Tile & Height: CERAMIC 2X2 TILES BELOW 45/-rps 7FEET",
        "Kitchen Wall Tile: DADO TILE 2X2 (2 FEET WALL HEIGHT) 45/-",
      ],
    },
    {
      title: "Doors & Windows",
      type: "list",
      items: [
        "Main Door Frame: ANY TEAK BELOW 2500/-CFT",
        "Main Door: SINGLE DOOR WITH ELEGANT DESGIN",
        "Bedroom Door Frames: ANY TEAK BELOW 2500/-CFT",
        "Bedroom Door: FLUSH DOORS BELOW 4000/-",
        "Bathroom Door: 1ST QUALITY WPC FRAME & PLAIN DOORS",
        "Windows: UPVC WITH PINNED GLASS 4MM",
        "Ventilators: UPVC LOUVERS WITH PINNED GLASS",
      ],
    },
    {
      title: "Flooring & Finishing",
      type: "list",
      items: [
        "Interior Paint: ASIAN PRIMIUM EMULSION OR EQUIVALENT",
        "Exterior Paint: ASIAN APEX OR EQUIVALENT BRANDS",
        "Handrails for Staircase: STAINLESS STEEEL (0r)M.S Grill",
        "Staircase Flooring: GRANITE BELOW 80/- PER SQFT",
        "Kitchen Counter Top: GRANITE BELOW 140/- PER SQFT",
        "Terrace: HEAT REFLECTOR PAINTS",
        "Floor Tile: VERTIFIED TILES 2X2 BELOW 55/-",
      ],
    },
    {
      title: "Additional Features",
      type: "list",
      items: [
        "Carparking/Portico/Balcony: ANTISKID TILES 45/",
        "AC Point Provisions: IN ALL BEDROOMS",
        "General Extra: ANTI-TERMITE TREATMENT",
        "Team Supports: SITE ENG HALF A DAY SITE VISIT DAILY",
        "Locks: DORSET/EUROPA",
        "Design & Drawings: FLOOR PLAN 2D & 3D,ELEVATION & STRUCTURAL",
      ],
    },
  ],
};

const ElitePackage = {
  title: {
    name: "Elite Package",
    price: "2499",
  },
  sections: [
    {
      title: "Overview",
      type: "text",
      content:
        "Our Elite Package offers exceptional quality construction with premium features and comprehensive architectural support for those seeking sophisticated design and superior materials.",
    },
    {
      title: "Design",
      type: "list",
      items: [
        "SCHEME DRAWING : ALL FLOORS (2D)",
        "ELEVATION DESIGN : (3D)",
        "HALF LAYOUT : ALL FLOORS (3D)",
        "ELECTRICAL DRAWINGS : ALL FLOORS (2D)",
        "PLUMBING DRAWING : ALL FLOORS (2D)",
        "WORKING DRAWING : ALL FLOORS (2D)",
        "STRUCTURAL DRAWINGS",
        "FURNITURE LAYOUT : ALL FLOORS (2D)",
        "ELEVATION DETAIL DRAWING : (2D)",
      ],
    },
    {
      title: "Project Management",
      type: "list",
      items: [
        "Site Engineer : Weekly 3 Days Site Visit",
        "Architect : Dedicated Architect through-out the Project. Material Selection Support.",
        "ENGINEER SHARED SITES/& DAILY 1 PHOTO",
      ],
    },
    {
      title: "Structure",
      type: "list",
      items: [
        "Basement Height : 4 feet",
        "Steel : PULKIT/JSW/VIZAG/",
        "Bricks : CHAMBER/AAC /INTERLOCKING",
        "Cement : DALMIA/ULTRATECH/CHETTINADU",
        "Fine Aggregate : M-SAND/P-SAND",
        "Concrete Grade : M20 | RMC for Roof",
        "Ceiling Height : 11 Feet (FFL to FFL)",
        "Basement Plastering : YES",
        "Parapet Wall : 3.5' Feet Height | 6\" Thick",
        "Cement: DALMIA/ULTRATECH/CHETTINADU",
        "Steel: PULKIT/JSW/VIZAG/",
        "Fine Aggregate: M-SAND/P-SAND",
        "Bricks: CHAMBER/AAC /INTERLOCKING",
        "Wire: FINOLEX/FEBROS OR EQUIVALENT",
        "Switches: GM /ANCHOR OR EQUIVALENT",
        "Water Tank: ASHIRWAD 3 LAYERS 2000LTR",
      ],
    },
    {
      title: "Plumbing & Sanitary",
      type: "list",
      items: [
        "Plumbing (Concealed CPVC): ASHIRWAD",
        "Plumbing Open PVC: ASHIRWAD",
        "Sanitary Fittings: PARRYWARE/SOMANY/KAG",
        "Taps & Valves: PARRYWARE/SOMANY/CERA/KAG",
        "Bathroom Floor Tile: ANTISKID 1X15 TILES BELOW 50/-",
        "Bathroom Wall Tile & Height: CERAMIC TILES 4X2 PREMIUM BRAND 8 FEET",
        "Kitchen Wall Tile: DADO TILE 2X2 (2 FEET WALL HEIGHT) 50/-",
      ],
    },
    {
      title: "Doors & Windows",
      type: "list",
      items: [
        "Main Door Frame: ANY TEAK BELOW 3000/-CFT",
        "Main Door: SINGLE DOOR WITH CNC CARVING",
        "Bedroom Door Frames: ANY TEAK BELOW 3000/-CFT",
        "Bedroom Door: FLUSH DOORS BELOW 5000/-",
        "Bathroom Door: PAINTED WPC FRAME & DOORS WITH GROOVING",
        "Windows: UPVC WITH GLASS 4MM",
        "Ventilators: UPVC LOUVERS WITH PINNED GLASS",
      ],
    },
    {
      title: "Flooring & Finishing",
      type: "list",
      items: [
        "Interior Paint: ASIAN ACE SHYNE OR BERGER EASY CLEAN",
        "Exterior Paint: ASIAN APEX OR EQUIVALENT BRANDS",
        "Handrails for Staircase: STAINLESS STEEL WITH TOUGHEND GLASS",
        "Staircase Flooring: GRANITE BELOW 90/-- PER SQFT",
        "Kitchen Counter Top: GRANITE BELOW 180/- PER SQFT",
        "Terrace: COOL ROOF",
        "Floor Tile: VERTIFIED TILES 2X4 BELOW 60/-",
      ],
    },
    {
      title: "Additional Features",
      type: "list",
      items: [
        "Carparking/Portico/Balcony: ANTISKID TILES 50/-",
        "AC Point Provisions: IN ALL ROOMS",
        "General Extra: ANTI-TERMITE TREATMENT",
        "Team Supports: ENGINEER SHARED SITES/& DAILY 1 PHOTO",
        "Locks: GODREJ",
        "Design & Drawings: 2D,3D,FURNITURE LAYOUT,STRUTURAL LAYOUT,ELEVATION,ELECTRICAL & PLUMBING",
      ],
    },
  ],
};

const LuxuryPackage = {
  title: {
    name: "Luxury Package",
    price: "2999",
  },
  sections: [
    {
      title: "Overview",
      type: "text",
      content:
        "Our Luxury Package represents the pinnacle of construction quality, featuring premium materials, top-tier brands, and comprehensive design services for the most discerning clients.",
    },
    {
      title: "Design",
      type: "list",
      items: [
        "SCHEME DRAWING : ALL FLOORS (2D)",
        "ELEVATION DESIGN : (3D)",
        "HALF LAYOUT : ALL FLOORS (3D)",
        "ELECTRICAL DRAWINGS : ALL FLOORS (2D)",
        "PLUMBING DRAWING : ALL FLOORS (2D)",
        "WORKING DRAWING : ALL FLOORS (2D)",
        "SOIL TEST REPORT",
        "STRUCTURAL DRAWINGS",
        "FURNITURE LAYOUT : ALL FLOORS (2D)",
        "ELEVATION DETAIL DRAWING : (2D)",
        "2D,3D,FURNITURE LAYOUT,STRUTURAL LAYOUT,ELEVATION,ELECTRICAL & PLUMBING",
      ],
    },
    {
      title: "Project Management",
      type: "list",
      items: [
        "Site Engineer : Exclusive Engineer",
        "Daily Photo Upload. Project Status Monitoring.",
        "Architect : Dedicated Architect through-out the Project. Stage wise Site Visit. Material Selection Support.",
        "EXCLUSIVE ENGINEER & ARCHITURAL SUPPORT/DAILY PHOTOS",
      ],
    },
    {
      title: "Structure",
      type: "list",
      items: [
        "Basement Height : 4 feet",
        "Steel : JSW/TATA",
        "Bricks : CHAMBER BRICKS/AAC BLOCKS/INTERLOCKING/POROTHERM BLOCK",
        "Cement : DALMIA/CHETTINADU/ULTRATECH/COROMANDEL",
        "Fine Aggregate : M-SAND/P-SAND",
        "Concrete Grade : M20 | RMC for Roof",
        "Ceiling Height : 12 Feet (FFL to FFL)",
        "Basement Plastering : YES WITH WATER PROOFING",
        "Parapet Wall : 3.5' Feet Height | 6\" Thick",
        "Cement: DALMIA/CHETTINADU/ULTRATECH/COROMANDEL",
        "Steel: JSW/TATA",
        "Fine Aggregate: M-SAND/P-SAND",
        "Bricks: CHAMBER BRICKS/AAC BLOCKS/INTERLOCKING/POROTHERM BLOCK",
        "Wire: FINOLEX GOLD/POLYCAB",
        "Switches: LEGRAND/FEBROS /HAVELLS",
        "Water Tank: SINTEX 5 LAYERS 2000LTR",
      ],
    },

    {
      title: "Plumbing & Sanitary",
      type: "list",
      items: [
        "Plumbing (Concealed CPVC): ASHIRWAD/FINOLEX",
        "Plumbing Open PVC: ASHIRWAD/FINOLEX",
        "Sanitary Fittings: JAQUAR/KOHLER/KEROVIT",
        "Taps & Valves: JAQUAR/KOHLER/KEROVIT/ROCO",
        "Bathroom Floor Tile: ANTISKID TILES 2X2 PREMIUM BRAND 70/-",
        "Bathroom Wall Tile & Height: CERAMIC TILES 4X2 PREMIUM BRAND 10 FEET",
        "Kitchen Wall Tile: DADO TILE 4X2 (2 FEET WALL HEIGHT) 70/-",
      ],
    },
    {
      title: "Doors & Windows",
      type: "list",
      items: [
        "Main Door Frame: FIRST QUALITY TEAK ABOVE 4500/-CFT",
        "Main Door: TAILOR MADE",
        "Bedroom Door Frames: 1ST QUALITY TEAK FRAME ABOVE 4000/-CFT",
        "Bedroom Door: FLUSH DOORS BELOW 6000/-",
        "Bathroom Door: WPC FRAME & DESIGNER DOORS",
        "Windows: UPVC COLOURED GLASS 4MM",
        "Ventilators: UPVC LOUVERS WITH PINNED GLASS",
      ],
    },
    {
      title: "Flooring & Finishing",
      type: "list",
      items: [
        "Interior Paint: ROYAL EMULSION OR EQUIVALENT",
        "Exterior Paint: ASIAN ULTIMA OR EQUIVALENT BRAND",
        "Handrails for Staircase: STAINLESS STEEEL(0r)M.S Grill",
        "Staircase Flooring: GRANITE BELOW 120/- PER SQFT",
        "Kitchen Counter Top: GRANITE BLACK GALAXY OR QUARTZ",
        "Terrace: COOL ROOF TOP BRANDS",
        "Floor Tile: VERTIFIED TILES PREMIUM BRANDS BELOW 80/-",
      ],
    },
    {
      title: "Additional Features",
      type: "list",
      items: [
        "Carparking/Portico/Balcony: ANTISKID TILES PREMIUM BRANDS",
        "AC Point Provisions: IN ALL ROOMS (EXCEPT KITCHEN & TOILET)",
        "General Extra: ANTI-TERMITE TREATMENT",
        "Team Supports: EXCLUSIVE ENGINEER & ARCHITURAL SUPPORT/DAILY PHOTOS",
        "Locks: GODREJ /YALE /EUROPA",
        "Design & Drawings: 2D,3D,FURNITURE LAYOUT,STRUTURAL LAYOUT,ELEVATION,ELECTRICAL & PLUMBING",
      ],
    },
  ],
};

const ServicePackage = {
  PriceBudgetPackage,
  standardPackage,
  premiumPackage,
  ElitePackage,
  LuxuryPackage,
};

export default ServicePackage;
